"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        number_letters = {}
        for c in s:
            n = number_letters.get(c)
            if not n:
                number_letters[c] = 1
            else:
                number_letters[c] = 1 + n

        for c in t:
            n = number_letters.get(c)
            if not n:
                return c
            else:
                number_letters[c] = n - 1

s = Solution()
print(s.findTheDifference("abcd", "abcd"))